[tool.poetry]
name = "yanki"
version = "0.1.0"
description = "Build Anki decks from text files containing YouTube URLs."
authors = ["Daniel Parks <dp+git@oxidized.org>"]
readme = "README.md"

[tool.poetry.scripts]
yanki = "yanki.cli:main"

[tool.poetry.dependencies]
python = "^3.12"
yt-dlp = "^2024.11.4"
genanki = "^0.13.1"
docutils = "^0.21.2"
ffmpeg-python = "^0.2.0"
colorlog = "^6.9.0"
click = "^8.1.8"

[tool.poetry.group.dev.dependencies]
pytest = "^8.3"
ruff = "^0.8.4"
pre-commit = "^4.0.1"
pytest-console-scripts = "^1.4.1"

[tool.pytest.ini_options]
script_launch_mode = "subprocess"

[tool.ruff]
line-length = 80

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
