name: PR checks

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

env:
  # Enable color in typos
  CLICOLOR: 1

jobs:
  format:
    name: ruff format
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - uses: astral-sh/ruff-action@v3
        with:
          args: "format --check"

  check:
    name: ruff check
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - uses: astral-sh/ruff-action@v3

  pytest:
    name: pytest
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - run: sudo apt-get update
      - run: sudo apt-get install -y ffmpeg
      - uses: astral-sh/setup-uv@v7
      - run: uv python install
      - run: uv run pytest --color=yes

  typos:
    name: typos
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - uses: crate-ci/typos@v1.38.1
