name: PR checks

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  # Enable color in typos
  CLICOLOR: 1

# These would more naturally be separate jobs, but GitHub actions “bills” each
# job separately and rounds up to the next minute, so four 10 second jobs “cost”
# my account 4 action minutes.
jobs:
  checks:
    name: Checks
    runs-on: ubuntu-latest
    timeout-minutes: 30
    permissions:
      security-events: write # SARIF reporting for zizmor

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - run: sudo apt-get update
      - run: sudo apt-get install -y ffmpeg
      - uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0
      - run: uv python install

      - name: ruff format
        uses: astral-sh/ruff-action@0ce1b0bf8b818ef400413f810f8a11cdbda0034b # v4.0.0
        if: ${{ !cancelled() }}
        with:
          args: "format --check"

      - name: ruff check
        uses: astral-sh/ruff-action@0ce1b0bf8b818ef400413f810f8a11cdbda0034b # v4.0.0
        if: ${{ !cancelled() }}

      - run: uv run pytest --color=yes
        if: ${{ !cancelled() }}
        shell: bash

      - uses: crate-ci/typos@f8a58b6b53f2279f71eb605f03a4ae4d10608f45 # v1.47.0
        if: ${{ !cancelled() }}

      - uses: zizmorcore/zizmor-action@5f14fd08f7cf1cb1609c1e344975f152c7ee938d # v0.5.6
        if: ${{ !cancelled() }}
        with:
          persona: pedantic
