name: PR checks

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

jobs:
  format:
    name: ruff format
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/ruff-action@v3
        with:
          args: "format --check"

  check:
    name: ruff check
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/ruff-action@v3

  pytest:
    name: pytest
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - run: sudo apt-get update
      - run: sudo apt-get install -y ffmpeg
      - uses: astral-sh/setup-uv@v5
      - run: uv python install
      - run: uv run pytest --color=yes
