name: PR checks

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  # Enable color in typos
  CLICOLOR: 1

# These would more naturally be separate jobs, but GitHub actions “bills” each
# job separately and rounds up to the next minute, so four 10 second jobs “cost”
# my account 4 action minutes.
jobs:
  checks:
    name: Checks
    runs-on: ubuntu-latest
    timeout-minutes: 30
    permissions:
      security-events: write # SARIF reporting for zizmor

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - run: sudo apt-get update
      - run: sudo apt-get install -y ffmpeg
      - uses: astral-sh/setup-uv@20cfd1bf945f4377ade1205e4dbc17946fc9a30d # v10.0.1
      - run: uv python install

      - name: ruff format
        uses: astral-sh/ruff-action@278981a28ce3188b1e39527901f38254bf3aac89 # v4.1.0
        if: ${{ !cancelled() }}
        with:
          args: "format --check"

      - name: ruff check
        uses: astral-sh/ruff-action@278981a28ce3188b1e39527901f38254bf3aac89 # v4.1.0
        if: ${{ !cancelled() }}

      - run: uv run pytest --color=yes
        if: ${{ !cancelled() }}
        shell: bash

      - uses: crate-ci/typos@d43b6c087ac471e2ea7b8af622ff15f05c0c365b # v1.50.1
        if: ${{ !cancelled() }}

      - uses: zizmorcore/zizmor-action@70fb788f84895a7701f5643d103d587e460b5c99 # v0.6.3
        if: ${{ !cancelled() }}
        with:
          persona: pedantic
